### ISSUE TITLE
Do we want to move the `trigger-link-change` action into here?

### ISSUE THREAD

**Issue by jukent** [ProjectPythia/cookbook-actions#70]
See title

**Comment by brian-rose** [comment]
If we intend the action to be triggered manually by clicking the button from inside each repo, then need to have some kind of "triggering" code present in the `.github/workflows/` directory.

We could move most of the actual code into a reusable workflow that lives here to simplify future maintenance. That's what we've done with most of the other actions. A workflow in each cookbook repo would have to call the reusable workflow.

**Comment by jukent** [comment]
So I think yes? I will look into this more.

**Comment by brian-rose** [comment]
Clarification: we decided to close this at today's IWG meeting because we don't see any maintenance benefit to packaging this code as a reusable workflow. The reason is that the action is only invoked once when a new Cookbook repo is created from the template.

If we make changes to the Template that require changes to the workflow, we'll make those changes in the Template repo.
